version: '3.7'

services:
  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: keycloak-postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./postgresql/backup:/bitnami/postgresql/backup
    ports:
      - "5433:5432"

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    image: keycloak-keycloak
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment: 
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=bitnami
      - DB_VENDOR=postgres
      - DB_ADDR=postgresql
      - DB_PORT=5432
      - DB_USER=bn_keycloak
      - DB_DATABASE=bitnami_keycloak

    volumes:
      - ./keycloak/theme_dkf:/opt/jboss/keycloak/themes/theme_dkf
      - ./keycloak/messages:/opt/jboss/keycloak/themes/base/login/messages

volumes:
  postgresql_data:
    driver: local
