version: '3.7'

services:
  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: keycloak-postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./postgresql/backup:/bitnami/postgresql/backup
    ports:
      - "5433:5432"

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    image: keycloak-keycloak
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/theme_dkf:/opt/bitnami/keycloak/themes/theme_dkf

volumes:
  postgresql_data:
    driver: local
